# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f12a1fdf7200edbb0bd8565bdbb86f335684cd9789d3b25f1234f85ae39fccfc9c92cd6483bc03f547e4649720b708bd1adc5ae895625a71847c67dc71a2261

test:
  secret_key_base: fd92d1b060e147b9ddeda4cf2f724aa4ae7d7b950cd33eed316c999eaffe6138dc30edfd39e6d1bb4b410ce5ed35de572146b54819205f11d9097068ea690174

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
